=== IvyZhao405/xml-tutorial/out/production/dom4j/hr.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hr">
        <!-- have to use this to include child labels -->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" minOccurs="1" maxOccurs="9999">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"></xs:minInclusive>
                                        <xs:maxInclusive value="65"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="salary" type="xs:integer"></xs:element>
                            <xs:element name="department">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dname" type="xs:string"></xs:element>
                                        <xs:element name="address" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="no" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IvyZhao405/xml-tutorial/dom4j/src/hr-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Human Resource Manegement System-->
<hr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hr.xsd">
	<employee no="3309">
		<name>ZhangSan</name>
		<age>23</age>
		<salary>4000</salary>
		<department>
			<dname>Accounting</dname>
			<address>xxxstreat-B103</address>
		</department>
	</employee>
	<employee no="3310">
		<name>Lisi</name>
		<age>23</age>
		<salary>3000</salary>
		<department>
			<dname>Engineering</dname>
			<address>xxxstreat-B104</address>
		</department>
	</employee>
</hr>
